engines:
  semgrep:
    enabled: true
    exclude_paths:
      - ".github/*/**"
      - "docs/**"
      - "coverage/**"
      - "packages/*/coverage/**"
    config:
      rules:
        - id: github-actions-pin-sha
          enabled: false