---
engines:
  semgrep:
    exclude_paths:
      - ".github/*/**"
      - "coverage/**"
      - "packages/*/coverage/**"
      - "packages/**/dist/**"
      # Ignore test sources and helpers
      - "**/*.test.ts"
      - "**/*.spec.ts"
      - "packages/**/__tests__/**"
      - "packages/**/test-utils/**"
    config:
      rules:
        - id: github-actions-pin-sha
          enabled: false
  eslint-9:
    exclude_paths:
      - ".github/*/**"
      - "coverage/**"
      - "packages/*/coverage/**"
      - "packages/**/dist/**"
      # Ignore test sources and helpers
      - "**/*.test.ts"
      - "**/*.spec.ts"
      - "packages/**/__tests__/**"
      - "packages/**/test-utils/**"
exclude_paths:
  - "packages/extensions/test-utils/test-fs.ts"
  - "packages/**/dist/**"
  - "packages/db/prisma/migrations/**"
  - ".github/*/**"
  - "packages/docs-site/docs/**"
  - "packages/docs-site/content/**"
  - "docs/**"
  - "coverage/**"
  - "scripts/**"
  - "**/*.config.js"
  - "**/*.config.cjs"
  - "**/*.config.mjs"