engines:
  semgrep:
    enabled: true
    exclude_paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "docs/**"
    config:
      rules:
        - id: github-actions-pin-sha
          enabled: false