name: 'Setup Node & pnpm'
description: 'Install Node.js and pnpm (with pnpm caching)'
inputs:
  node:
    description: 'Node.js version (e.g., 20)'
    required: true
  pnpm:
  description: 'pnpm version (e.g., 10.16.1). Optional; if omitted, uses package.json#packageManager.'
  required: false

runs:
  using: 'composite'
  steps:
    - name: Install pnpm (standalone binary on PATH)
      uses: pnpm/action-setup@36de12bed180fa130ed56a35e7344f2fa7a820ab # v4
      with:
        # When version is omitted, the action respects packageManager from package.json
        version: ${{ inputs.pnpm }}
        standalone: true

    - name: Install Node.js (enable pnpm cache)
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: pnpm
        cache-dependency-path: |
          pnpm-lock.yaml
          **/pnpm-lock.yaml

    - name: Show tool versions
      shell: bash
      run: |
        node -v
        pnpm -v
