# setup-node-pnpm/action.yml
name: 'Setup Node & pnpm'
description: 'Install Node.js, pnpm'
inputs:
  node:
    description: 'Node.js version'
    required: true
  pnpm:
    description: 'pnpm version'
    required: true
  runs:
    using: 'composite'
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
          cache: 'pnpm'
          cache-dependency-path: |-
            pnpm-lock.yaml
            **/pnpm-lock.yaml
