name: Setup Node & pnpm
description: Install Node.js and pnpm (via corepack) with caching and verification
inputs:
  node:
    description: 'Node.js major/minor version (e.g. 20)'
    required: true
  pnpm:
    description: 'pnpm version (e.g. 9.0.0 or 9)'
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node }}
        cache: pnpm

    - name: Enable corepack & activate pnpm
      shell: bash
      run: |
        set -euo pipefail
        echo "Activating pnpm@${{ inputs.pnpm }} via corepack"
        corepack enable
        # Support shorthand major version or full semver
        corepack prepare pnpm@${{ inputs.pnpm }} --activate
        which pnpm || { echo 'pnpm not found after corepack prepare' >&2; exit 1; }
        pnpm -v

    - name: Print environment diagnostics (debug)
      if: ${{ runner.debug == '1' }}
      shell: bash
      run: |
        echo PATH=$PATH
        which node
        which pnpm
        node -v
        pnpm -v
