name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4  → pinned
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: ./.github/workflows/_setup-node-pnpm.yml
        with: {
          node: '20',
          pnpm: '9'
        }
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: ./.github/workflows/_setup-node-pnpm.yml
        with: {
          node: '20',
          pnpm: '9'
        }
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: ./.github/workflows/_setup-node-pnpm.yml
        with: {
          node: '20',
          pnpm: '9'
        }
      - run: pnpm install --frozen-lockfile
      - run: pnpm test -- --run